services:
  caddy:
    image: caddy:latest
    container_name: caddy
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./site:/srv
      - ./data:/data
      - ./config:/config
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
    networks:
      - jellyfin_bridge       # Comment if you dont use jellyfin.
    restart: unless-stopped

networks:
  jellyfin_bridge:            # Comment if you dont use jellyfin.
    name: jellyfin_bridge     # Comment if you dont use jellyfin.
    external: true            # Comment if you dont use jellyfin.
