services:
  samba:
    image: dockurr/samba
    container_name: samba
    ports:
      - 445:445
    volumes:
      - /mnt/data:/storage
      - ./smb.conf:/etc/samba/smb.conf:ro
      - ./users.conf:/etc/samba/users.conf:ro
    restart: unless-stopped
